email:
  mail-smtp-host: smtp.163.com
  mail-transport-protocol: smtp
  mail-smtp-auth: true
  username: m18233138990@163.com
  password: hxj123456

server:
  port: 8082

# SPRING AUTOCONFIGURE
spring:
  resources:
    cache-period: 31556926
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss Z
    locale: zh_CN
  serialization:
    indent_output: true
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 10
      min-idle: 2
      max-active: 80
      max-wait: -1

dataSource:
  master:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/onlystore?useUnicode=yes&characterEncoding=UTF-8"
    username: root
    password: root
    max-active: 20
    initial-size: 3
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false

#
#mybatis:
#  config-location: classpath:/mybatis-config.xml
#  mapperLocations: classpath:/mapper/**/*.xml

# LIQUIBASE
liquibase:
  change-log: classpath:/db/changelog.xml

# HTTPInvoker exporter
httpinvoker:
  type: exporter
  master-server: true
  scan-paths:
    - com.han.onlystore.base.service
  url-prefix: /remoting/

